### ISSUE TITLE
Tensor dimension mis-match during evaluation and training

### ISSUE THREAD

**Issue by meghana17** [matejgrcic/DenseFlow#1]
Hi! I'm seeing this error when using the evaluation and train command for ImageNet32

Loaded weights for model at 22/22 epochs
Traceback (most recent call last):
  File "/content/DenseFlow/experiments/image/eval_loglik.py", line 72, in <module>
    bpd = dataset_elbo_bpd(model, eval_loader, device=device, double=eval_args.double)
  File "/content/DenseFlow/denseflow/utils/loss.py", line 81, in dataset_elbo_bpd
    bpd += elbo_bpd(model, x).cpu().item() * len(x)
  File "/content/DenseFlow/denseflow/utils/loss.py", line 28, in elbo_bpd
    return loglik_bpd(model, x)
  File "/content/DenseFlow/denseflow/utils/loss.py", line 12, in loglik_bpd
    return - model.log_prob(x).sum() / (math.log(2) * x.shape.numel())
  File "/content/DenseFlow/denseflow/flows/flow.py", line 33, in log_prob
    x, ldj = transform(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/DenseFlow/experiments/image/model/flow_modules.py", line 127, in forward
    eta, delta_ll = self.cross_unit_coupling(g_in, self.blocks[i-1])
  File "/content/DenseFlow/experiments/image/model/flow_modules.py", line 114, in cross_unit_coupling
    eta_hat = mu + torch.exp(log_scale) * eta
RuntimeError: The size of tensor a (64) must match the size of tensor b (16) at non-singleton dimension 3

and with --k 200
File "/content/DenseFlow/experiments/image/eval_loglik.py", line 75, in <module>
    bpd = dataset_iwbo_bpd(model, eval_loader, k=eval_args.k, kbs=eval_args.kbs, device=device, double=eval_args.double)
  File "/content/DenseFlow/denseflow/utils/loss.py", line 106, in dataset_iwbo_bpd
    bpd += iwbo_bpd(model, x, k=k, kbs=kbs).cpu().item() * len(x)
  File "/content/DenseFlow/denseflow/utils/loss.py", line 57, in iwbo_bpd
    if kbs: return - iwbo_batched(model, x, k, kbs).sum() / (x.numel() * math.log(2))
  File "/content/DenseFlow/denseflow/utils/loss.py", line 44, in iwbo_batched
    ll_stack = model.log_prob(x_stack)
  File "/content/DenseFlow/denseflow/flows/flow.py", line 33, in log_prob
    x, ldj = transform(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/DenseFlow/experiments/image/model/flow_modules.py", line 127, in forward
    eta, delta_ll = self.cross_unit_coupling(g_in, self.blocks[i-1])
  File "/content/DenseFlow/experiments/image/model/flow_modules.py", line 114, in cross_unit_coupling
    eta_hat = mu + torch.exp(log_scale) * eta
RuntimeError: The size of tensor a (3200) must match the size of tensor b (16) at non-singleton dimension 3

I'm able to generate samples but not get the bpd scores.

**Comment by matejgrcic** [comment]
Hi!

Thanks, for the notification.
This is caused by passing the wrong argument to `cross_unit_coupling` function.
I've updated the code, please pull the last commit.

Kind regards,
Matej
